### ISSUE TITLE
APK Mirror doesn't work

### ISSUE THREAD

**Issue by captn3m0** [micro-a5k/google-sync-addon#1] opened 2017-11-14 20:28 UTC
It currently does this:

```
/usr/bin/zip
wget google-sync-addon/sources/files/app/GoogleContactsSyncAdapter.apk -U Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0 http://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=246810
--2017-11-15 01:57:00--  http://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=246810
Resolving www.apkmirror.com... 104.19.134.58, 104.19.136.58, 104.19.132.58, ...
Connecting to www.apkmirror.com|104.19.134.58|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=246810 [following]
--2017-11-15 01:57:00--  https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=246810
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Connecting to www.apkmirror.com|104.19.134.58|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.apkmirror.com [following]
--2017-11-15 01:57:01--  https://www.apkmirror.com/
Reusing existing connection to www.apkmirror.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘google-sync-addon/sources/files/app/GoogleContactsSyncAdapter.apk’

google-sync-add     [ <=>                                                                                          ]  27.95K  --.-KB/s    in 0.06s   

2017-11-15 01:57:01 (458 KB/s) - ‘google-sync-addon/sources/files/app/GoogleContactsSyncAdapter.apk’ saved [189293]


ERROR: The file 'google-sync-addon/sources/files/app/GoogleContactsSyncAdapter.apk' is corrupted.

```

The file itself is just HTML. Was considering download the pico opengapps, and extracting the apks from there.

**Comment by ale5000-git** [comment] 2017-11-16 03:10
@captn3m0: It should be fixed now, please try it and report back.

**Comment by ale5000-git** [comment] 2017-11-20 22:11
The problem is fixed, if you have other problems please open a new ticket.

**Closed by ale5000-git** 2017-11-20 22:11 UTC
Labels: bug

**Comment by captn3m0** [comment] 2017-11-24 17:53
Can confirm this works
